version: '3'
services:
    swoft:
        container_name: swoft
        image: swoft/swoft
        ports:
            - "81:80"
            - "8099:8099"
        volumes:
            - ./:/var/www/swoft
        stdin_open: true
        tty: true
        entrypoint: php /var/www/swoft/bin/swoft ws:start
#        command: php /var/www/swoft/bin/swoft ws:start
