version: '3'
services:
    swoft:
        container_name: swoft
        image: swoft/swoft
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/swoft
        stdin_open: true
        tty: true
        command: php /var/www/swoft/bin/swoft start
